export const FRONTEND_URL = process?.env?.FRONTEND_URL ?? "http://localhost:3000/"
export const BACKEND_URL = process?.env?.BACKEND_URL ?? "http://localhost:8080/api"
export const AUTH0_USERNAME = process?.env?.AUTH0_USERNAME ?? ""
export const AUTH0_PASSWORD = process?.env?.AUTH0_PASSWORD ?? ""
export const AUTH0_DOMAIN = process?.env?.VITE_AUTH0_DOMAIN ?? ""
export const PERMISSION_BASE_URL = "http://localhost:8080/api"